site_name: CookBook
theme:
  name: material
  language: zh
  features:
    - search.highlight
    - toc.integrate
  palette:

    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: light mode

    # Toggle dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: dark mode
plugins:
  - search:
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/landers1037
      name: Fork me on Github
markdown_extensions:
  - toc:
      permalink: true